name: Build Wheels

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-wheels:
    name: Build wheels for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DEBIAN_FRONTEND: noninteractive
      NEEDRESTART_MODE: a
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout pystk2-gymnasium
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies for PySuperTuxKart2
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake \
            g++ \
            gcc \
            libsdl2-dev \
            build-essential

      - name: Install Python build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Checkout PySuperTuxKart2 dependency
        uses: actions/checkout@v4
        with:
          repository: ml-arena/pystk2
          ref: '257c2107f'
          path: pystk2-build

      - name: Build PySuperTuxKart2 wheel
        run: |
          cd pystk2-build
          python -m build --wheel
          echo "=== PySuperTuxKart2 wheel built ==="
          ls -lh dist/

      - name: Install PySuperTuxKart2 wheel
        run: |
          pip install pystk2-build/dist/*.whl

      - name: Build pystk2-gymnasium wheel
        run: |
          python -m build --wheel
          echo "=== pystk2-gymnasium wheel built ==="
          ls -lh dist/

      - name: Test wheel installation
        run: |
          pip install dist/*.whl
          python -c "import pystk2_gymnasium; print(f'pystk2-gymnasium version: {pystk2_gymnasium.__version__}')"
          python -c "import pystk2; print('PySuperTuxKart2 imported successfully')"

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-py${{ matrix.python-version }}-linux-amd64
          path: |
            pystk2-build/dist/*.whl
            dist/*.whl
          retention-days: 90

      - name: Create release and upload wheels
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pystk2-build/dist/*.whl
            dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
