name: Build Wheels

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-wheels:
    name: Build wheels for Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DEBIAN_FRONTEND: noninteractive
      NEEDRESTART_MODE: a
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Checkout pystk2-gymnasium
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies for PySuperTuxKart2
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            cmake \
            g++ \
            gcc \
            build-essential \
            libsdl2-dev \
            libsdl2-2.0-0 \
            pkg-config \
            zlib1g-dev \
            libpng-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libharfbuzz-dev

      - name: Install Python build tools
        run: |
          python -m pip install --upgrade pip
          pip install build wheel poetry-core poetry-dynamic-versioning twine

      - name: Verify SDL2 installation
        run: |
          pkg-config --modversion sdl2 || echo "SDL2 not found via pkg-config"
          ldconfig -p | grep libSDL2 || echo "libSDL2 not found in ldconfig"
          find /usr -name "SDL2Config.cmake" 2>/dev/null || echo "SDL2Config.cmake not found"

      - name: Set CMake environment for SDL2
        run: |
          echo "CMAKE_PREFIX_PATH=/usr:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV

      - name: Build pystk2-gymnasium wheel
        run: |
          python -m build --wheel
          echo "=== pystk2-gymnasium wheel built ==="
          ls -lh dist/

      - name: Test wheel installation
        run: |
          pip install dist/*.whl
          python -c "import pystk2_gymnasium; print(f'pystk2-gymnasium version: {pystk2_gymnasium.__version__}')"
          python -c "import pystk2; print('PySuperTuxKart2 imported successfully')"

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-py${{ matrix.python-version }}-linux-amd64
          path: dist/*.whl
          retention-days: 90

      - name: Create release and upload wheels
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
        run: |
          # For GitHub Packages, use organization scope
          # python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*.whl
          echo "Wheel published to GitHub Release. Configure PyPI token for full PyPI publishing."
